version: '3.8'

services:
  bot:
    build: ./bot_image
    container_name: bot_container
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    restart: always
    networks:
      - bot_network

  db:
    build: ./db_image
    container_name: db_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bot_network

  db_slave:
    build: ./db_repl_image
    container_name: db_repl_container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5433:5432"
    restart: always
    environment:
      - PGPASSWORD=repl_user
    command: |
      bash -c "
      rm -rf /var/lib/postgresql/data/*
      until pg_basebackup -R -h db -U repl_user -D /var/lib/postgresql/data -P
      do
        echo 'Waiting for primary to connect...'
        sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
